traefik_stack_dir: "{{ paths.app_root }}/traefik"
traefik_config_dir: "{{ traefik_stack_dir }}/config"
traefik_letsencrypt_dir: "{{ traefik_config_dir }}/letsencrypt"

traefik_compose_project_name: homelab-traefik

traefik_image: "traefik:v3.6.7"
# Лучше потом зафиксировать на конкретный tag или digest, а не latest
# Но у этого образа нет других тегов кроме latest
traefik_avahi_image: "hardillb/traefik-avahi-helper:latest"

traefik_container_name: homeserver-traefik
traefik_avahi_container_name: homeserver-traefik-avahi-helper

traefik_dashboard_host: "traefik.home.local"

# Порты
traefik_http_port: 80
# Когда появится https вернуть true
traefik_enable_https: false
traefik_https_port: 443

# Прямой порт dashboard по умолчанию отключён.
traefik_enable_direct_dashboard_port: false
traefik_dashboard_direct_port: 8080

traefik_dashboard_auth_user: "admin"
traefik_dashboard_auth_password: ""

# На случай проблем с AppArmor/DBus у helper
traefik_avahi_privileged: false
