- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

    - size: full
      widgets:
        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Traefik
              url: http://traefik.home.local
              check-url: http://homeserver-traefik:8080/ping
              icon: auto-invert sh:traefik-dark
            - title: Glances
              url: http://glances.home.local
              check-url: http://homeserver-glances:61208/api/4/status
              icon: auto-invert sh:glances-dark

    - size: small
      widgets:
        - type: weather
          location: Kaliningrad, Russia
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "12h"

